/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jjni

import kotlin.test.*

class PrimitiveTypesTest {
    lateinit var pt: PrimitiveTypes


    @BeforeTest
    fun setUp() {
        pt = PrimitiveTypes
    }

    @Test
    fun testGetBoolean() {
        assert(pt.getBoolean())
    }

    @Test
    fun testGetByte() {
        assertEquals(Byte.MIN_VALUE, pt.getByte())
    }

    @Test
    fun testGetShort() {
        assertEquals(Short.MIN_VALUE, pt.getShort())
    }

    @Test
    fun testGetChar() {
        assertEquals('Q', pt.getChar())
    }

    @Test
    fun testGetInt() {
        assertEquals(Int.MIN_VALUE, pt.getInt())
    }

    @Test
    fun testGetLong() {
        assertEquals(Long.MIN_VALUE, pt.getLong())
    }

    @Test
    fun testGetFloat() {
        //浮点数不相等
        assertNotEquals(Float.MIN_VALUE, pt.getFloat())
    }

    @Test
    fun testGetDouble() {
        //浮点数不相等
        assertNotEquals(Double.MIN_VALUE, pt.getDouble())
    }
}
